cap_filter:
  event: 
    - "Fire"
    - "Earthquake"
    - "Flood"
    - "Hazardous Material"
    - "Severe Weather"
    - "Power Outage"
  urgency: 
    - "Immediate"
    - "Expected"
    - "Future"
  severity: 
    - "Extreme"
    - "Severe"
    - "Moderate"
    - "Minor"
  certainty: 
    - "Observed"
    - "Likely"
  area:
    - "Building A"
    - "Building B"
    - "Building C"
    - "Parking Lot"
    - "Surrounding Area"
  responseType:
    - "Shelter"
    - "Evacuate"
    - "Prepare"
    - "Monitor"
    - "AllClear"
  status:
    - "Actual"
    - "Exercise"
    - "System"
    - "Test"
  msgType:
    - "Alert"
    - "Update"
    - "Cancel"
  scope:
    - "Public"
    - "Restricted"
    - "Private"
  optionalFields:
    - "headline"
    - "description"
    - "instruction"
    - "contact"
    - "sent"
    - "effective"
    - "onset"
    - "expires"
