dispatch_threshold: 10

dispatch_interval: 10

emergencies:
  Flood:
    type: floor
    danger_floors: [0]
  Earthquake:
    type: all
  Hazardous Material:
    type: all
  Severe Weather:
    type: all
  Power Outage:
    type: all
  Fire:
    type: zone
    danger_zone:
      x1: 100
      x2: 500
      y1: 100
      y2: 500
      z1: 0
      z2: 1
