# Configuration for dispatch thresholds and intervals.
# These settings control how frequently and how many positions should be processed 
# before dispatching aggregated data to other microservices.

dispatch_threshold: 10  # The number of positions to process before dispatching data to other services.
dispatch_interval: 10   # The time interval (in seconds) between dispatches to other services.

# Emergency event configurations specifying which areas are considered dangerous
# depending on the event type.

emergencies:
  # Configuration for the 'Flood' event type.
  Flood:
    type: floor  # Defines the type of event (e.g., 'floor', 'zone', 'all')
    # Floors considered dangerous during a flood.
    danger_floors: [0]  # Floor 0 is defined as dangerous during a flood.
    safe_node_type: "stairs"

  # Configuration for the 'Earthquake' event type.
  Earthquake:
    type: all  # Defines that all floors or areas are considered dangerous during an earthquake.
    safe_node_type: "outdoor"

  # Configuration for the 'Hazardous Material' event type.
  Hazardous Material:
    type: all  # Defines that all floors or areas are considered dangerous during hazardous material exposure.
    safe_node_type: "outdoor"

  # Configuration for the 'Severe Weather' event type.
  Severe Weather:
    type: all  # Defines that all floors or areas are considered dangerous during severe weather events.
    safe_node_type: "outdoor"

  # Configuration for the 'Power Outage' event type.
  Power Outage:
    type: all  # Defines that all floors or areas are considered dangerous during a power outage.
    safe_node_type: "outdoor"

  # Configuration for the 'Fire' event type.
  Fire:
    type: zone  # Defines the event type as affecting a specific zone (rather than a floor or area).
    # Danger zone coordinates for the fire event, specifying the area that is considered dangerous.
    danger_zone:
      x1: 100  # Lower bound of the x-coordinate for the danger zone.
      x2: 500  # Upper bound of the x-coordinate for the danger zone.
      y1: 100  # Lower bound of the y-coordinate for the danger zone.
      y2: 500  # Upper bound of the y-coordinate for the danger zone.
      z1: 0    # Lower bound of the z-coordinate (floor level) for the danger zone.
      z2: 1    # Upper bound of the z-coordinate (floor level) for the danger zone.
    safe_node_type: "outdoor"      